//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public int VehicleID { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string LicencePlate { get; set; }
        public Nullable<int> KM { get; set; }
        public string BodyType { get; set; }
        public Nullable<int> DailyPrice { get; set; }
        public string Fuel { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public string Series { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
